export enum RoleCode {
  LGA_COORDINATOR = 'LGA_COORDINATOR',
  WARD_COORDINATOR = 'WARD_COORDINATOR',
  PU_AGENT = 'PU_AGENT',
  CLIENT_ADMIN = 'CLIENT_ADMIN',
  SYSTEM_ADMIN = 'SYSTEM_ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN',
  ASPIRANT = 'ASPIRANT',
}
