export const APP_QUEUES = {
  mail: 'MAIL_QUEUE',
  file: 'FILE_QUEUE',
} as const;

export const QueueDictionary = {
  SEND_MAIL: 'SEND_MAIL',
  PROCESS_LGA_UPLOAD_WITH_STATE_ID: 'PROCESS_LGA_UPLOAD_WITH_STATE_ID',
  PROCESS_LGA_UPLOAD_GENERIC: 'PROCESS_LGA_UPLOAD_GENERIC',
  PROCESS_WARD_UPLOAD_WITH_LGA_ID: 'PROCESS_WARD_UPLOAD_WITH_LGA_ID',
  PROCESS_WARD_UPLOAD_GENERIC: 'PROCESS_WARD_UPLOAD_GENERIC',
  PROCESS_POLLING_UNIT_UPLOAD_WITH_WARD_ID:
    'PROCESS_POLLING_UNIT_UPLOAD_WITH_WARD_ID',
  PROCESS_POLLING_UNIT_UPLOAD_GENERIC: 'PROCESS_POLLING_UNIT_UPLOAD_GENERIC',
} as const;
